# Generated by Django 5.2.3 on 2025-11-15 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='created_time',
            new_name='start_time',
        ),
        migrations.RemoveField(
            model_name='task',
            name='updated_time',
        ),
    ]
